---
- name: Get serial numbers from IOS and NX-OS devices
  hosts: all
  gather_facts: true
  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_IP') }}"  # Replace with your NetBox URL
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"  # Get from environment variable
    device_status: "active"
    validate_certs: true

  tasks:
    - name: Include IOS tasks
      import_tasks: ios/ios_tasks.yml
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Include NX-OS tasks
      import_tasks: nxos/nxos_tasks.yml
      when: ansible_network_os == 'cisco.nxos.nxos'

    - name: Include Juniper tasks
      import_tasks: junos/junos_tasks.yml
      when: ansible_network_os == 'junipernetworks.junos.junos'