---
collections:
  - name: junipernetworks.junos
    version: "5.0.0"
  - name: ansible.netcommon
    version: "3.0.0"
  - name: cisco.ios
    version: "4.0.0"
  - name: cisco.nxos
    version: "4.0.0"
