- name: Create device in NetBox
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ device_name }}"
      device_type: "{{ device_type }}"
      device_role: "{{ device_role }}"
      site: "{{ site }}"
      status: "{{ device_status | default('active') }}"
      serial: "{{ device_serial | default(omit) }}"
      asset_tag: "{{ device_asset_tag | default(omit) }}"
      description: "{{ device_description | default(omit) }}"
    state: present
    validate_certs: "{{ validate_certs | default(true) }}"
  register: device_result
